%% to plot the relationship between mean activation and set size, for various inhibition strengths.
% (Monotonus.eps)

mean_activ=load('avrg_data3_a2.2_n30.mat');
S = mean_activ.S;
%%
figure('Units', 'pixels', ...
'Position', [100 100 500 375]);
hold on
cc = load('C_data_monotonus.mat');
C_data = cc.C_data_monotonus;
xx=15:50;
aa = C_data(1,1);  bb = C_data(1,2) ;
yy=(xx-aa)./bb;
lfit1 = line(xx,yy);

xx=8:34;
aa = C_data(2,1);  bb = C_data(2,2) ;
yy=(xx-aa)./bb;
lfit2 = line(xx,yy);


xx=2:25;
aa = C_data(4,1);  bb = C_data(4,2) ;
yy=(xx-aa)./bb;
lfit4 = line(xx,yy);

xx=0:10;
aa = C_data(15,1);  bb = C_data(15,2) ;
yy=(xx-aa)./bb;
lfit15 = line(xx,yy);
%%
% S=ones(size(S));
M = 1:50 ;
B=1:15;

% myfit = fittype('a*x + b*x^2 + c*x^3 + d',...
% 'dependent',{'y'},'independent',{'x'},...
% 'coefficients',{'a','b','c','d'});
% fit1=fit([1:50]',S(1,1:50,1)','smoothingspline');
% fit4=fit([1:50]',S(4,1:50,1)','smoothingspline');
% fit15=fit([1:50]',S(15,1:50,1)','smoothingspline');



line1=line(1:50,S(1,1:50,1));
line2=line(1:50,S(2,1:50,1));
line4=line(1:50,S(4,1:50,1));
line10=line(1:50,S(10,1:50,1));
line15=line(1:50,S(15,1:50,1));

line1m=line(21:50,S(1,21:50,1));
line2m=line(12:28,S(2,12:28,1));
line4m=line(5:18,S(4,5:18,1));
line15m=line(1:4,S(15,1:4,1));

% xx = linspace(1,50,150);
% linefit1=line(xx,fit1(xx));
% linefit4=line(xx,fit4(xx));
% linefit15=line(xx,fit15(xx));

set(lfit1                        , ...
  'LineStyle'       , '--'        , ...
  'Color'           , [0 0 0]         );
set(lfit2                        , ...
  'LineStyle'       , '--'        , ...
  'Color'           , [0 0 0]         );

set(lfit4                        , ...
  'LineStyle'       , '--'        , ...
  'Color'           , [0 0 0]         );
set(lfit15                        , ...
  'LineStyle'       , '--'        , ...
  'Color'           , [0 0 0]         );

% set(linefit1                        , ...
%   'LineStyle'       , '--'        , ...
%   'Color'           , [0 0 .75]         );
% set(linefit4                        , ...
%   'LineStyle'       , '--'        , ...
%   'Color'           , [0 0 .75]         );
% set(linefit15                        , ...
%   'LineStyle'       , '--'        , ...
%   'Color'           , [0 0 .75]         );
set(line1                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 4           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [1 .6 .6] );
set(line2                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 4           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [.7 .7 .7] );
set(line15                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 4           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [0.6 .6 1] );
set(line10                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 4           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [.9 .9 .6] );
set(line4                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , 'o'         ,...
  'MarkerSize'      , 4           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [0.6 1 .6] );

set(line1m                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [1 0 0] );
set(line2m                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [.3 .3 .3] );
set(line15m                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , '.'         ,...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [0 0 1] );
set(line4m                            , ...
  'LineStyle'       , 'none'      , ...
  'Marker'          , 'o'         ,...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , 'none'      , ...
  'MarkerFaceColor' , [0 1 0] );


% hTitle  = title ('');
hXLabel = xlabel('SetSize(input Numerosity)'                     );
hYLabel = ylabel('Mean Activation'                      );

c=0.0995;
C=0.1;
hText   = text(10, 800, ...
  sprintf('htext....'));

hLegend = legend( ...
  [line1,line2, line4,line10, line15], ...
  '\beta = 0.01' , ...
  '\beta = 0.02' , ...
  '\beta = 0.04'  , ...
  '\beta = 0.10' , ...
  '\beta = 0.15'  , ...
  'location', 'Northwest' );
%
set( gca                       , ...
    'FontName'   , 'Helvetica' );
% set([hTitle,hXLabel, hYLabel, hText], ...
set([hXLabel, hYLabel, hText], ...
     'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel, hText]  , ...
    'FontSize'   , 10          );
% set( hTitle                    , ...
%     'FontSize'   , 12          , ...
%     'FontWeight' , 'bold'      );
mn=min(min(S(:,1:50,1)));
mx=max(max(S(:,1:50,1)));
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , mn:(mx-mn)/10:mx, ...
  'XTick'       , [0 5 10 15 20 25 30 35 40 45 50], ...
  'LineWidth'   , 1         );

set(gcf, 'PaperPositionMode', 'auto');
print -depsc2 Monotonus.eps
